#!/usr/bin/env python3
"""Build the compact, self-contained, non-live v2 contract fixture."""
import json
from pathlib import Path
from operations.registry import load_registries
ROOT=Path(__file__).resolve().parents[1]; T="2026-07-13T00:00:00Z"
def main():
 assets,sources,metrics=load_registries(); source_map={s["sourceId"]:s for s in sources["sources"]}; aid=next(a for a in assets["assets"] if a["resortId"]=="hotham" and a["assetClass"]=="run")
 selected_sources=[source_map["hotham_official_report"],source_map["hotham_mountainops_runs"]]; hashes={"hotham_official_report":"a"*64,"hotham_mountainops_runs":"b"*64}
 def cap(cid,sid):
  s=source_map[sid];h=hashes[sid]
  return {"captureId":cid,"resortId":"hotham","sourceId":sid,"sourceLayer":s["layer"],"sourceRole":s["sourceRole"],"retrievedAt":T,"responseAt":T,"sourceReportedAt":T,"operationalDate":"2026-07-13","httpStatus":200,"contentType":"application/xml" if "report" in sid else "application/json","payloadHash":h,"rawPayloadRef":f"fixtures/raw/{h}.json","parserVersion":"2-fixture","retrievalStatus":"ok","freshnessMinutes":0,"assetRegistryRevision":assets["contentHash"],"sourceInventoryRevision":sources["contentHash"],"metricCatalogueRevision":metrics["contentHash"],"warnings":[]}
 def snow(oid,cid,scope,signal,state,raw,meaning,confidence="unverified",numeric=None,field="Snowmaking",mapped=False,upstream_id=None,upstream_name=None,warnings=[]):
  return {"observationId":oid,"captureId":cid,"resortId":"hotham","scope":scope,"subjectAssetId":aid["assetId"] if mapped else None,"upstreamAssetId":upstream_id,"upstreamName":upstream_name,"area":None,"signalType":signal,"normalizedState":state,"numericValue":numeric,"unit":"count" if numeric is not None else None,"rawValue":raw,"sourceField":field,"observationRole":"measurement","semanticMeaning":meaning,"interpretationConfidence":confidence,"observedAt":T,"effectiveFrom":None,"effectiveTo":None,"notes":[],"warnings":warnings}
 metric={"observationId":"depth-107","captureId":"cap-report","resortId":"hotham","metricKey":"machine_made_depth_cm","value":107,"unit":"cm","valueStatus":"observed","observationRole":"measurement","scope":"location","subjectId":None,"locationLabel":"Snowmaking areas","observedAt":T,"effectiveFrom":None,"effectiveTo":None,"sourceField":"AvSnowdepthinSnowmakingAreas","rawValue":"107","semanticQualifier":"reported snowmaking-area depth","interpretationConfidence":"high","notes":[]}
 status={"observationId":"run-status","captureId":"cap-live","resortId":"hotham","assetId":aid["assetId"],"upstreamAssetId":aid["sourceMappings"][0]["upstreamAssetId"],"upstreamName":aid["displayName"],"assetClass":"run","operationalStatus":"open","statusReason":[],"rawStatus":"Open","observationRole":"live_actual","scheduled":None,"expectedToOpen":None,"openTime":None,"closeTime":None,"queueMinutes":None,"condition":None,"groomed":True,"snowmakingObservationIds":["run-no"],"observedAt":T,"effectiveFrom":None,"effectiveTo":None,"interpretationConfidence":"high","warnings":[]}
 aggregate=[{"observationId":"morning-17","captureId":"cap-report","resortId":"hotham","assetClass":"lift","area":None,"status":"expected","numerator":17,"denominator":None,"denominatorScope":"expected_today","observationRole":"morning_plan","observedAt":T,"sourceField":"ExpectedLifts","rawValue":"17","notes":[]},{"observationId":"live-12","captureId":"cap-live","resortId":"hotham","assetClass":"lift","area":None,"status":"open","numerator":12,"denominator":20,"denominatorScope":"service_records","observationRole":"live_actual","observedAt":T,"sourceField":"Status","rawValue":"12/20","notes":[]}]
 raw=[{"payloadHash":hashes[sid],"sourceId":sid,"sourceUrl":source_map[sid]["url"],"firstCapturedAt":T,"responseAt":T,"httpStatus":200,"contentType":"application/xml" if "report" in sid else "application/json","rawPayloadRef":f"fixtures/raw/{hashes[sid]}.json","parserVersion":"2-fixture"} for sid in hashes]
 payload={"schemaVersion":"alpine.operations-export.v2","identitySchemaVersion":"alpine.resort-identities.v1","assetRegistrySchemaVersion":"alpine.operations-assets.v1","assetRegistryRevision":assets["contentHash"],"assetRegistryCompleteness":"partial","sourceInventoryRevision":sources["contentHash"],"sourceInventoryCompleteness":"partial","metricCatalogueRevision":metrics["contentHash"],"generatedAt":T,"windowStart":T,"windowEnd":T,"producer":"fixture only; not a live artifact","assets":[aid],"captures":[cap("cap-report","hotham_official_report"),cap("cap-live","hotham_mountainops_runs")],"metricObservations":[metric],"snowmakingObservations":[snow("plant-standby","cap-report","resort","plant_state","standby","On Standby","literal report-level plant/report state","high"),snow("runs-five","cap-report","resort","runs_snowmaking_count","unknown","5","unverified reported count; not guns or proven active runs",numeric=5,field="RunsSnowmaking"),snow("run-no","cap-live","asset","run_snowmaking_flag","unknown","NO","unverified per-run upstream flag",mapped=True,upstream_id=aid["sourceMappings"][0]["upstreamAssetId"],upstream_name=aid["displayName"],warnings=["Raw NO does not establish plant inactivity"]),snow("feed-none","cap-live","resort","run_snowmaking_flag","none_flagged",{"rowsExamined":89,"affirmativeFlags":0},"feed-level summary only; no individual row was affirmative",field="Snowmaking[*]")],"assetStatusObservations":[status],"aggregateObservations":aggregate,"narratives":[],"conflicts":[],"diagnostics":{"warnings":[],"unknownSourceFields":[],"unmappedAssetCount":0},"rawPayloads":raw,"sourceInventory":selected_sources}
 out=ROOT/"tests/fixtures/operations/v2/example_operations_export_v2.json";out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n")
if __name__=="__main__":main()
